function [Figdata, hFig, hAxes, hLine] = WaveInitEyeDisplay
btnColor=get(0,'DefaultUIControlBackgroundColor');

% Position the figure on right extended screen at the bottom
screenUnits=get(0,'Units');
screenSize=get(0,'ScreenSize');
set(0,'Units',screenUnits);
figWidth=440;
figHeight=512;
figPos=[40 40  ...
      figWidth                    figHeight];
  
% Create the figure window.
hFig=figure(...                    
   'Color'             ,btnColor                 ,...
   'IntegerHandle'     ,'off'                    ,...
   'DoubleBuffer'      ,'on'                     ,...
   'MenuBar'           ,'none'                   ,...
   'HandleVisibility'  ,'on'                     ,...
   'Name'              ,'Eye Position'  ,...
   'Tag'               ,'Eye Position'  ,...
   'NumberTitle'       ,'off'                    ,...
   'Units'             ,'pixels'                 ,...
   'Position'          ,figPos                   ,...
   'UserData'          ,[]                       ,...
   'Colormap'          ,[]                       ,...
   'Pointer'           ,'arrow'                  ,...
   'Visible'           ,'off'                     ...
   );

% Create Data subplot.
set(hFig,'Visible','on');
hAxes(1) = axes(...
   'Position'          , [0.08 0.3 0.55 0.55],...
   'Parent'            , hFig, ...
   'XLim'              , [-25 25],...
   'YLim'              , [-25 25]...
   );

i=1:33;
Figdata.xcoord(i)=5*cos(i*pi/16);
Figdata.ycoord(i)=5*sin(i*pi/16);
hLine(3) = plot(1*Figdata.xcoord,1*Figdata.ycoord,'Parent',hAxes(1));
hLine(2) = line('XData',0,'YData',0,'marker','+');  % eye position
hLine(1) = line('XData',0,'YData',0,'marker','s'); % stimulus position
xlim([-25,25]);
ylim([-25,25]);
% markerradii = ((4/2.54)*72)/4;

% Label the plot.
xlabel('X');
ylabel('Y');

% Create Eye X subplot.

hAxes(2) = axes(...
   'Position'          , [0.6700 0.650 0.30 0.15],...
   'Parent'            , hFig,...
   'XLim'              , [0 3000],...
   'YLim'              , [-10 10]...
   );
%when sample at 500 Hz, show eye data in last 6s
% hLine(6) = line('XData',200,'YData',10, 'marker', 'v');
% Label the plot.
title('Eye X');

% Create Eye Y subplot.

hAxes(3) = axes(...
   'Position'          , [0.670 0.350 0.30 0.15],...
   'Parent'            , hFig,...
   'XLim'              , [0 3000],...
   'YLim'              , [-10 10]...
   );
%when sample at 500 Hz, show eye data in last 6s
% Label the plot.
xlabel('Time');
title('Eye Y');

Figdata.figure = hFig;
Figdata.axes = hAxes;
Figdata.line = hLine;
set(hFig,'Visible','on','UserData',Figdata);
